%==============================================================
% Returns object's output for a given input vector. 
%
% @param U : input vector of size (X x 4)
% @returns : object's output of size (X x 4)
%==============================================================
function Y = simulate(U)

    % Get length of the simulation 
    simulation_time = size(U, 1);

    % Initialize output vector
    Y = zeros(simulation_time, 3);

    % Simulate
    for i = 1:simulation_time

        if (i > 4)
            Y(i, :) = object( ...
                U(i - 1, 1), U(i - 2, 1), U(i - 3, 1), U(i - 4, 1), ...
                U(i - 1, 2), U(i - 2, 2), U(i - 3, 2), U(i - 4, 2), ...
                U(i - 1, 3), U(i - 2, 3), U(i - 3, 3), U(i - 4, 3), ...
                U(i - 1, 4), U(i - 2, 4), U(i - 3, 4), U(i - 4, 4), ...
                Y(i - 1, 1), Y(i - 2, 1), Y(i - 3, 1), Y(i - 4, 1), ...
                Y(i - 1, 2), Y(i - 2, 2), Y(i - 3, 2), Y(i - 4, 2), ...
                Y(i - 1, 3), Y(i - 2, 3), Y(i - 3, 3), Y(i - 4, 3) ...
            );
        elseif ( i > 3 )
            Y(i, :) = object( ...
                U(i - 1, 1), U(i - 2, 1), U(i - 3, 1),           0, ...
                U(i - 1, 2), U(i - 2, 2), U(i - 3, 2),           0, ...
                U(i - 1, 3), U(i - 2, 3), U(i - 3, 3),           0, ...
                U(i - 1, 4), U(i - 2, 4), U(i - 3, 4),           0, ...
                Y(i - 1, 1), Y(i - 2, 1), Y(i - 3, 1),           0, ...
                Y(i - 1, 2), Y(i - 2, 2), Y(i - 3, 2),           0, ...
                Y(i - 1, 3), Y(i - 2, 3), Y(i - 3, 3),           0 ...
            );
        elseif ( i > 2 )
            Y(i, :) = object( ...
                U(i - 1, 1), U(i - 2, 1),           0,           0, ...
                U(i - 1, 2), U(i - 2, 2),           0,           0, ...
                U(i - 1, 3), U(i - 2, 3),           0,           0, ...
                U(i - 1, 4), U(i - 2, 4),           0,           0, ...
                Y(i - 1, 1), Y(i - 2, 1),           0,           0, ...
                Y(i - 1, 2), Y(i - 2, 2),           0,           0, ...
                Y(i - 1, 3), Y(i - 2, 3),           0,           0 ...
            );
        elseif ( i > 1 )
            Y(i, :) = object( ...
                U(i - 1, 1),           0,           0,           0, ...
                U(i - 1, 2),           0,           0,           0, ...
                U(i - 1, 3),           0,           0,           0, ...
                U(i - 1, 4),           0,           0,           0, ...
                Y(i - 1, 1),           0,           0,           0, ...
                Y(i - 1, 2),           0,           0,           0, ...
                Y(i - 1, 3),           0,           0,           0 ...
            );
        else
            Y(i, :) = object( ...
                          0,           0,           0,           0, ...
                          0,           0,           0,           0, ...
                          0,           0,           0,           0, ...
                          0,           0,           0,           0, ...
                          0,           0,           0,           0, ...
                          0,           0,           0,           0, ...
                          0,           0,           0,           0 ...
            );
        end

    end
end

